# Generated by Django 3.1.3 on 2020-11-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vendedor_senha_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='vendedor',
        ),
    ]
